### ISSUE TITLE
Nothing is working. Everything is updated.

### ISSUE THREAD

**Issue by kaySpaz** [wifiphisher/wifiphisher#1155]
Hey guys. Love the project. Recently reinstalled a Kali dual-boot  on a mid 2014 Macbook Pro and I am getting an error with the UI when I run the program with no CLI arguments ( Just wifiphisher )  I get an error that looks like the below picture. 
When I run "wifiphisher -i wlan1 -kN -e "FREE WIFI" -p oauth-login -kB --logging --logpath /root/phisher_log.log" I get the correct UI screen listing extensions and mac addresses but I cant connect to the AP. Used Android iPhone and MacOs to try to connect as 'victim'

I have tried reinstalling, doesn't fix anything. On fresh install I still get same errors. I then booted up my Vbox system updated everything then I GOT THE SAME ERRORS SOMEHOW. 

I update with apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y

# uname -r
4.19.0-kali5-amd64

# git show | grep commit
commit aab4efe986c75a8d822f9b0dfa2b148801734837

# iw
Interface wlan0
	ifindex 2
	wdev 0x1
	addr REDACTED
	ssid REDACTED
	type managed
	wiphy 0
	txpower 200.00 dBm
Interface wlan1
	ifindex 3
	wdev 0x100000001
	addr REDACTED
	type managed
	wiphy 1
	txpower 30.00 dBm

# iwconfig:
wlan0     IEEE 802.11  ESSID:""  
          Mode:Managed  Frequency:5.2 GHz  Access Point: REDACTED
          Bit Rate=405 Mb/s   Tx-Power=200 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=68/70  Signal level=-42 dBm  
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0
lo        no wireless extensions.
wlan1     IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=30 dBm   
          Retry short  long limit:2   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
<<Log File>> For # wifiphisher -i wlan1 -kN -e "FREE WIFI" -p oauth-login -kB --logging --logpath /root/phisher_log.log

2019-07-27 17:41:49,113 -        wifiphisher.pywifiphisher - INFO - Starting Wifiphisher
2019-07-27 17:41:49,126 -        wifiphisher.common.opmode - INFO - Starting OP_MODE5 (0x5)
2019-07-27 17:41:49,225 -        wifiphisher.pywifiphisher - INFO - Selecting wfphshr-wlan1 for deauthentication and wlan1 for the rogue Access Point
2019-07-27 17:41:49,225 -        wifiphisher.pywifiphisher - INFO - Changing wlan1 MAC address to REDACTED
2019-07-27 17:41:49,226 -        wifiphisher.pywifiphisher - INFO - Unblocking interfaces
2019-07-27 17:41:50,256 -        wifiphisher.pywifiphisher - INFO - Selecting OAuth Login Page template
2019-07-27 17:41:51,615 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
2019-07-27 17:41:52,237 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
2019-07-27 17:41:52,280 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
2019-07-27 17:41:52,484 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
2019-07-27 17:41:52,492 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
2019-07-27 17:41:52,535 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
2019-07-27 17:41:53,002 -    wifiphisher.extensions.deauth - INFO - Target deauth BSSID found: REDACTED
Picture of UI after # wifiphisher is run
<img width="960" alt="61843311-6668a580-ae58-11e9-9edd-68eb0bfa446c" src="https://user-images.githubusercontent.com/45438350/62000923-ec772d00-b0a0-11e9-807d-ccf5c97792d3.png">

**Comment by tabujarwar** [comment]
I am having this same issue. Everything with wifiphisher was working fine until I installed some Kali Linux 2019.3 packages.

**Comment by kaySpaz** [comment]
I have been RACKING MY BRAINS for about TWO WEEKS now. Tried everything I know. But hey that's why I love Linux. When you get stumped you are guaranteed to learn something.

**Comment by sophron** [comment]
I'll have a look as soon as possible.

**Comment by sophron** [comment]
I just pushed a commit that fixes this. Please update to the latest revision and let me know.

**Comment by tabujarwar** [comment]
Thanks. Is the latest version the one on GitHub? Is the one in the Kali repo the latest version?

**Comment by sophron** [comment]
The latest is the one on Github. If you clone the repo on Github now, you'll get the latest.

**Comment by tabujarwar** [comment]
Hello! Thank you. Everything seems to be working now. I will test more later and let you know if there are any issues. Thanks again!

**Comment by kaySpaz** [comment]
Still getting same error in the UI after running wifiphisher with no arguements. I did a fresh install as well.

**Comment by sophron** [comment]
It shouldn't be the same error, maybe something similar. Can you post a screenshot? Also what's the output of `git show | grep commit`?

**Comment by kaySpaz** [comment]
root@block:~/wifiphisher# git show | grep commit
commit 53779384d09f3039b2ec897c7c91079c57965ae0

When I run: wifiphisher -kN -iNM
I get the typical log without errors but when UI loads this pops up:
![2019-07-31_14-48](https://user-images.githubusercontent.com/45438350/62247232-aa046780-b3a2-11e9-862b-044ffda3f08f.png)

I refresh the UI by resizing terminal which gives me an incomplete list of AP's in the area. The UI error seems to stop the AP search as it will only display AP's discovered before the error pops up.

I also updated and wifiphisher on a Vbox install. Same error comes up.

**Comment by sophron** [comment]
Can you run wifiphisher with `python bin/wifiphisher` from within the project's directory? Are you still getting the same error?

**Comment by kaySpaz** [comment]
root@block:~# python bin/wifiphisher
python: can't open file 'bin/wifiphisher': [Errno 2] No such file or directory

**Comment by tabujarwar** [comment]
Hello! I tried it again and it didn't work. Same issue as KaySpaz. Thank you.

**Comment by kaySpaz** [comment]
Hey i got a chance to rerun from bin.
# root@block:~/wifiphisher/bin# python wifiphisher

![bin-wifiphisher](https://user-images.githubusercontent.com/45438350/62313603-6830fb00-b44e-11e9-97d6-4040fde4a43d.png)

**Comment by sophron** [comment]
Thanks, I'll have a look again today.

**Comment by kaySpaz** [comment]
Really appreciate it.

**Comment by sophron** [comment]
Hi guys,

I pushed another fix. Can you re-clone & re-install the project and try again?

**Comment by kaySpaz** [comment]
Awesome! No error this time. Only problem is signal strength all reads 0%... I have alfa awus036nh nic and have never had any problems with signal strength before.

wifiphisher -i wlan0 -iI int0 -iNM -kN --logging -lP /root/wifiphisherLogs/log1.log


![network_select](https://user-images.githubusercontent.com/45438350/62565408-f5f05a00-b843-11e9-9b80-cdd954ad72bb.png)

**Comment by vanserna** [comment]
Hi, I'm having the same problem. No signal strength and same error lines. I already re clone, please help!

**Comment by vanserna** [comment]
![15661904363061144936577316028012](https://user-images.githubusercontent.com/54258992/63240023-83a05200-c213-11e9-99fe-ce759dcb8596.jpg)

**Comment by vanserna** [comment]
![15661922238165269558513669351696](https://user-images.githubusercontent.com/54258992/63240992-a7fe2d80-c217-11e9-9a0b-34baae518cee.jpg)
