### ISSUE TITLE
Wifiphisher does not start! - HELP ME

### ISSUE THREAD

**Issue by madh4k** [wifiphisher/wifiphisher#1522]
I saw many people have the same issue.
Can someone help me fix this error?

Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 33, in <module>
    sys.exit(load_entry_point('wifiphisher==1.4', 'console_scripts', 'wifiphisher')())
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 728, in run
    engine.start()
  File "/usr/lib/python3/dist-packages/wifiphisher/pywifiphisher.py", line 502, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/lib/python3/dist-packages/wifiphisher/common/interfaces.py", line 647, in unblock_interface
    if pyw.isblocked(card):
  File "/usr/lib/python3/dist-packages/pyric/pyw.py", line 625, in isblocked
    return rfkill.soft_blocked(idx), rfkill.hard_blocked(idx)
  File "/usr/lib/python3/dist-packages/pyric/utils/rfkill.py", line 163, in soft_blocked
    raise pyric.error(errno.ENODEV,"No device at {0}".format(idx))
pyric.error: [Errno 19] No device at None

![Screenshot_2022-06-11_13_59_57](https://user-images.githubusercontent.com/26027638/173187337-77f91bcf-e622-4f39-ad33-df01fe62b61f.png)

**Comment by anees-tech** [comment]
Still this error

> 

>

**Comment by baroukh404** [comment]
I have fixed this error, running on parrotOs 5 or kali latest version, I have the same error but I fixed this yeasterday.
Try to install using apt , if not work, try this: 
- clone the repositorie 
- go to wifiphisher folder 
- run python3 setup.py , if you get get an error , you must install all dependecies to run
- python3 setup install 
- python3 setup build
- back to launch wifiphisher binarie in bin/wifiphihser. 

I'm not good in english but tell me if this work. Thanks sir.

**Comment by ZXF-BW** [comment]
I have the same error, too. Here is how I fixed it:

1. you just simply need to open the rfkill.py file in PyRIC module

![Screenshot_2022-07-05_02-17-20](https://user-images.githubusercontent.com/75823656/177203387-20186139-8f4e-4304-b8b6-efffd3e018d6.png)

2. go to line 86 and find the code

     `'soft':RFKILL_STATE[s],`

     then change it to

     `'soft':RFKILL_STATE[s % 2],`

     save the file and quit. Run wifiphisher. Finally, It works.

It seems like a bug of module PyRIC. To figure out why, I followed the error message and trace back, printed the list `RFKILL_STATE` and the value of variable `s` of this code, and found that the former equals to `[True, False]` and the latter may equal to 2. When `s` equals to 2, it raised `IndexError: list index out of range`. Make sure index of list `RFKILL_STATE` less than 2, then bug is fixed.

**Comment by madh4k** [comment]
> I have fixed this error, running on parrotOs 5 or kali latest version, I have the same error but I fixed this yeasterday. Try to install using apt , if not work, try this:
> 
>     * clone the repositorie
> 
>     * go to wifiphisher folder
> 
>     * run python3 setup.py , if you get get an error , you must install all dependecies to run
> 
>     * python3 setup install
> 
>     * python3 setup build
> 
>     * back to launch wifiphisher binarie in bin/wifiphihser.
> 
> 
> I'm not good in english but tell me if this work. Thanks sir.

I tried... It's now working
anyways thanks for help

**Comment by madh4k** [comment]
> I have the same error, too. Here is how I fixed it:
> 
>     1. you just simply need to open the rfkill.py file in PyRIC module
> 
> 
> ![Screenshot_2022-07-05_02-17-20](https://user-images.githubusercontent.com/75823656/177203387-20186139-8f4e-4304-b8b6-efffd3e018d6.png)
> 
>     2. go to line 86 and find the code
>        `'soft':RFKILL_STATE[s],`
>        then change it to
>        `'soft':RFKILL_STATE[s % 2],`
>        save the file and quit. Run wifiphisher. Finally, It works.
> 
> 
> It seems like a bug of module PyRIC. To figure out why, I followed the error message and trace back, printed the list `RFKILL_STATE` and the value of variable `s` of this code, and found that the former equals to `[True, False]` and the latter may equal to 2. When `s` equals to 2, it raised `IndexError: list index out of range`. Make sure index of list `RFKILL_STATE` less than 2, then bug is fixed.

![Screenshot_2022-07-24_13_35_02](https://user-images.githubusercontent.com/26027638/180645265-d52de9d6-2d46-4d23-af83-e507be1a9380.png)
I changed  'soft':RFKILL_STATE[s], to 'soft':RFKILL_STATE[s % 2], and now when I open wifiphisher is telling me No access point has been discovered yet!
Thanks for helping

**Comment by thaynes91** [comment]
I am still getting the same error code after changing the interfaces.py as well as the line 86 in rfkill.py

**Comment by brandontict** [comment]
> I have the same error, too. Here is how I fixed it:
> 
>     1. you just simply need to open the rfkill.py file in PyRIC module
> 
> 
> ![Screenshot_2022-07-05_02-17-20](https://user-images.githubusercontent.com/75823656/177203387-20186139-8f4e-4304-b8b6-efffd3e018d6.png)
> 
>     2. go to line 86 and find the code
>        `'soft':RFKILL_STATE[s],`
>        then change it to
>        `'soft':RFKILL_STATE[s % 2],`
>        save the file and quit. Run wifiphisher. Finally, It works.
> 
> 
> It seems like a bug of module PyRIC. To figure out why, I followed the error message and trace back, printed the list `RFKILL_STATE` and the value of variable `s` of this code, and found that the former equals to `[True, False]` and the latter may equal to 2. When `s` equals to 2, it raised `IndexError: list index out of range`. Make sure index of list `RFKILL_STATE` less than 2, then bug is fixed.

Thank you for sharing , that fixed one of my issues. 
Seems RFkill_unblock is buggy as well ? 

When running wifiphisher ,  latest Kali build, updated kernel. I receive , 
`Traceback (most recent call last):
  File "/pentest/802.11/wifiphisher/bin/./wifiphisher", line 24, in <module>
    run()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 762, in run
    engine.start()
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/pywifiphisher.py", line 536, in start
    self.network_manager.unblock_interface(ap_iface)
  File "/usr/local/lib/python3.10/dist-packages/wifiphisher-1.4-py3.10.egg/wifiphisher/common/interfaces.py", line 649, in unblock_interface
    pyw.unblock(card)
  File "/usr/local/lib/python3.10/dist-packages/pyric/pyw.py", line 628, in unblock
    rfkill.rfkill_unblock(idx)
  File "/usr/local/lib/python3.10/dist-packages/pyric/utils/rfkill.py", line 135, in rfkill_unblock
    fout.write(rfke)
TypeError: write() argument must be str, not bytes
` 

I am currently trying to fix 

`File "/usr/local/lib/python3.10/dist-packages/pyric/utils/rfkill.py", line 135, in rfkill_unblock` 

Any one having any luck?  What does the OP mean by " I CHANGED INTERFACES.PY "  ? 

I've been using wifiphisher for years . Last year or so this has been my issue .
