### ISSUE TITLE
NETWORK IS DOWN WHEN I START THE WIFIPHISHER

### ISSUE THREAD

**Issue by gudi13** [wifiphisher/wifiphisher#655]
hello friends, when i start up the wifiphisher on kali after the instalation, the network down and only re-instaling the kali on virtualbox to work again, and if i start the wifiphisher down again. 
someone can help me?

**Comment by chadchadders** [comment]
Exactly the same issue. And it makes my interface play up, wont connect to network manager etc etc. Had to re-install the whole kali virtual box. 

Could it be a bug with the most recent release?

**Comment by anakin1028** [comment]
Can you use the command : `git show | grep commit` let us know which version do you use?
Also is it OK for the V1.3 version?

**Comment by antekirtt** [comment]
I have the same issue. Just after stopping the wifiphisher the Network Manager is not coming back. Using systemctl restart NetworkManager does not solve the situation.
Instead of reinstalling kali, it is possible to purge the manager (apt-get purge network-manager network-manager-gnome), and reinstall both, which solve at least the issue to not have the network working.
I'm using the last version.

**Comment by anakin1028** [comment]
Have you tried the command `nmcli n on`?

@blackHatMonkey do you think you can implement the signal handler to release the resouces when `keyboardInterrupt` happens?

**Comment by blackHatMonkey** [comment]
@anakin1028 I will look in to it 😄 .

**Comment by alex-nov-dev** [comment]
I have a problem after with the network after launch wifiphisher.
The program itself works fine, I liked it very much.
Well, after I turn it off, I lose the network and WLAN on LAN

**Comment by anakin1028** [comment]
@alex-nov-dev, Yes. You will lose the network since we have killed the `wpa_supplicant` and `dhclient`  lunched by the `NetworkManager`. Have you tried to restart the service of NetworkManager? If restarting the networkmanager service still not work, you may try `nmcli n on` as I have mentioned in the previous comment.

**Comment by Esser420** [comment]
The machine state after the program finishes should be the same as when the program started.
I think the program should unmanage an interface itself and restart the network-manager, then when it finishes it should restore the management to that interface.
This avoids killing the NetworkManager altogether which is kind of a dirty way of achieving your purpose.

**Comment by anakin1028** [comment]
@Esser420 Thanks for the suggestion. Indeed we have a PR for fixing this issue. The main root cause of this problem is not because we kill the NetworkManager process.

The root cause is we toggle down the `NetworkManager` by `dbus` in the start of `wifiphisher` although we will toggle up in the end of `wifiphisher`, but if wifiphisher is not cleanly shut down, this step cannot be done successfully.

after #713 is merged, this should be fixed. 

Another thing we need to improve is as you said we should not use `airmon-ng check kill` to kill the interfering processes but not restart thus processes in the end.

**Comment by lancillotto** [comment]
I found that maybe

service network-manager stop
rm /var/lib/NetworkManager/NetworkManager.state
service network-manager start

restore functionality.

**Comment by sophron** [comment]
#751 was recently merged and may has solved this. Please update to the latest revision and try again.

**Comment by ll3N1GmAll** [comment]
I am using the github version of wifiphisher cloned today (5/22/19) and I am still getting the network-manager kill issue when Ctrl+C is issued. A reboot resolves the issue; but everything is down and all attempts to restart it fail. Tried these steps to no avail:
service network-manager stop
rm /var/lib/NetworkManager/NetworkManager.state
service network-manager start
nmcli n on

**Comment by BrandonLaneZz** [comment]
When I plug in my alfa wifi adapter, wifiphisher gives error and won't start. IF I unplug alfa card and only use on board wifi, wifiphisher starts. I need 2 separate wifi cards to execute correctly, right?
